apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-pv
  labels:
    app: keycloak
    component: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-keycloak
  local:
    path: /home/alien/keycloak/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists