apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: his-keycloak
spec:
  clusterIP: None
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: jgroups
      port: 7600
      targetPort: 7600
  publishNotReadyAddresses: true
