apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secrets
  namespace: his-keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN_USER: admin
  KEYCLOAK_ADMIN_PASSWORD: admin@123
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: admin@123
  POSTGRES_DB: keycloak
