apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: his-keycloak
  labels:
    app: keycloak
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 7600
      targetPort: 7600
      protocol: TCP
      name: jgroups
  selector:
    app: keycloak