apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: his-keycloak
spec:
  replicas: 2
  serviceName: keycloak
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.0.2
        args: ["start"]
        env:
        # Database configuration
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgres.his-keycloak.svc.cluster.local
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_SCHEMA
          value: public
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_DB_USER
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_DB_PASSWORD
        
        # Bootstrap admin for first-time setup
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_ADMIN_USER
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        
        # --- LOCALHOST HOSTNAME CONFIGURATION ---
        - name: KC_HOSTNAME
          value: "localhost" # Use localhost for local browser access
        - name: KC_HOSTNAME_PORT
          value: "30801" # The NodePort you are using
        - name: KC_HOSTNAME_STRICT
          value: "false" # Allows access via other hostnames too
        - name: KC_HTTP_ENABLED
          value: "true"
        
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/keycloak/data
          name: keycloak-data
  volumeClaimTemplates:
  - metadata:
      name: keycloak-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: keycloak-local-path
