apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-data-pv-1
  labels:
    app: keycloak
    component: keycloak
    replica: "1"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-keycloak
  local:
    path: /home/alien/keycloak/keycloak-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
