---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_DB: "keycloak"
  POSTGRES_USER: "keycloak"
  POSTGRES_PASSWORD: "YourStrongPasswordHere"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "YourAdminPasswordHere"
