apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: his-keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-pod-reader
  namespace: his-keycloak
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-pod-reader-binding
  namespace: his-keycloak
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: his-keycloak
roleRef:
  kind: Role
  name: keycloak-pod-reader
  apiGroup: rbac.authorization.k8s.io
