apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db-init
  namespace: his-keycloak
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init-db
        image: postgres:17-alpine
        command:
        - /bin/sh
        - -c
        - |
          echo "Initial wait for Postgres service..."
          sleep 10

          echo "Attempting to connect and initialize DB (up to 10 retries)..."
          for i in {1..10}; do
            if PGPASSWORD=$(POSTGRES_PASSWORD) psql -h postgres -U $(POSTGRES_USER) -d postgres -c "SELECT 1;" >/dev/null 2>&1; then
              echo "Postgres connection successful! Initializing DB on attempt $i."
              break
            fi
            echo "Connection failed on attempt $i/10. Retrying in 5s..."
            sleep 5
          done

          # Fail if all retries failed
          if ! PGPASSWORD=$(POSTGRES_PASSWORD) psql -h postgres -U $(POSTGRES_USER) -d postgres -c "SELECT 1;" >/dev/null 2>&1; then
            echo "FATAL: Failed to connect to Postgres after 10 retries."
            exit 1
          fi

          # Create role and DB conditionally, grant privileges
          PGPASSWORD=$(POSTGRES_PASSWORD) psql -h postgres -U $(POSTGRES_USER) -d postgres -v ON_ERROR_STOP=1 <<EOSQL
          DO \$\$
          BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$$KEYCLOAK_DB_USER') THEN
              CREATE ROLE $$KEYCLOAK_DB_USER WITH LOGIN PASSWORD '$$KEYCLOAK_DB_PASSWORD' CREATEDB;
            ELSE
              ALTER ROLE $$KEYCLOAK_DB_USER WITH LOGIN PASSWORD '$$KEYCLOAK_DB_PASSWORD' CREATEDB;
            END IF;
          END
          \$\$;

          DO \$\$
          BEGIN
            IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '$$KEYCLOAK_DB') THEN
              EXECUTE format('CREATE DATABASE %I', '$$KEYCLOAK_DB');
            END IF;
          END
          \$\$;

          GRANT ALL PRIVILEGES ON DATABASE $$KEYCLOAK_DB TO $$KEYCLOAK_DB_USER;

          \c $$KEYCLOAK_DB;

          GRANT ALL PRIVILEGES ON SCHEMA public TO $$KEYCLOAK_DB_USER;
          GRANT ALL ON ALL TABLES IN SCHEMA public TO $$KEYCLOAK_DB_USER;
          GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $$KEYCLOAK_DB_USER;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $$KEYCLOAK_DB_USER;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $$KEYCLOAK_DB_USER;
          EOSQL

          echo "DB initialization completed successfully!"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_PASSWORD
        - name: KEYCLOAK_DB
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_DB
        - name: KEYCLOAK_DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_DB_USER
        - name: KEYCLOAK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_DB_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
