apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-db-init
  namespace: his-keycloak
  labels:
    app: postgres-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-db
        image: postgres:17-alpine
        command:
        - /bin/sh
        - -c
        - |
          set -e
          PGPASSWORD=$(POSTGRES_PASSWORD) psql -h postgres -U $(POSTGRES_USER) -d postgres -v ON_ERROR_STOP=1 <<EOSQL
          DO \$\$
          BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$$KEYCLOAK_DB_USER') THEN
              CREATE ROLE $$KEYCLOAK_DB_USER WITH LOGIN PASSWORD '$$KEYCLOAK_DB_PASSWORD' CREATEDB;
            ELSE
              ALTER ROLE $$KEYCLOAK_DB_USER WITH LOGIN PASSWORD '$$KEYCLOAK_DB_PASSWORD' CREATEDB;
            END IF;
          END
          \$\$;
          SELECT 'CREATE DATABASE $$KEYCLOAK_DB' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$$KEYCLOAK_DB')\gexec;
          GRANT ALL PRIVILEGES ON DATABASE $$KEYCLOAK_DB TO $$KEYCLOAK_DB_USER;
          \c $$KEYCLOAK_DB;
          GRANT ALL PRIVILEGES ON SCHEMA public TO $$KEYCLOAK_DB_USER;
          GRANT ALL ON ALL TABLES IN SCHEMA public TO $$KEYCLOAK_DB_USER;
          GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $$KEYCLOAK_DB_USER;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $$KEYCLOAK_DB_USER;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $$KEYCLOAK_DB_USER;
          EOSQL
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_PASSWORD
        - name: KEYCLOAK_DB
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_DB
        - name: KEYCLOAK_DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_DB_USER
        - name: KEYCLOAK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: KEYCLOAK_DB_PASSWORD
        # Wait for Postgres service
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              PGPASSWORD=$(POSTGRES_PASSWORD) psql -h postgres -U $(POSTGRES_USER) -d postgres -c "SELECT 1;"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
