apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: his-keycloak
spec:
  storageClassName: local-storage-keycloak
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi