apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: his-keycloak
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef: { name: keycloak-postgres-secrets, key: POSTGRES_USER }
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef: { name: keycloak-postgres-secrets, key: POSTGRES_PASSWORD }
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef: { name: keycloak-postgres-secrets, key: POSTGRES_DB }
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: keycloak-local-path
      volumeName: keycloak-postgres-pv
      resources:
        requests:
          storage: 10Gi
